name = "MetaGraphsNext"
uuid = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
version = "0.8.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"

[weakdeps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[extensions]
MetaGraphsNextJLD2Ext = ["Graphs", "JLD2"]

[compat]
Graphs = "1.4.1"
JLD2 = "0.1.11, 0.2, 0.3, 0.4, 0.5, 0.6"
SimpleTraits = "0.9"
julia = "1.10"
